// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/MOOVE-Network/location_service/services (interfaces: DurationService,NotificationService)

// Package mocks is a generated GoMock package.
package mocks

import (
	db "github.com/MOOVE-Network/location_service/db"
	services "github.com/MOOVE-Network/location_service/services"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockDurationService is a mock of DurationService interface
type MockDurationService struct {
	ctrl     *gomock.Controller
	recorder *MockDurationServiceMockRecorder
}

// MockDurationServiceMockRecorder is the mock recorder for MockDurationService
type MockDurationServiceMockRecorder struct {
	mock *MockDurationService
}

// NewMockDurationService creates a new mock instance
func NewMockDurationService(ctrl *gomock.Controller) *MockDurationService {
	mock := &MockDurationService{ctrl: ctrl}
	mock.recorder = &MockDurationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDurationService) EXPECT() *MockDurationServiceMockRecorder {
	return m.recorder
}

// GetDuration mocks base method
func (m *MockDurationService) GetDuration(arg0, arg1 db.Location, arg2 time.Time) (services.DurationMetrics, error) {
	ret := m.ctrl.Call(m, "GetDuration", arg0, arg1, arg2)
	ret0, _ := ret[0].(services.DurationMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDuration indicates an expected call of GetDuration
func (mr *MockDurationServiceMockRecorder) GetDuration(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDuration", reflect.TypeOf((*MockDurationService)(nil).GetDuration), arg0, arg1, arg2)
}

// MockNotificationService is a mock of NotificationService interface
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// SendNotification mocks base method
func (m *MockNotificationService) SendNotification(arg0 string, arg1 map[string]interface{}, arg2 string) error {
	ret := m.ctrl.Call(m, "SendNotification", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification
func (mr *MockNotificationServiceMockRecorder) SendNotification(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockNotificationService)(nil).SendNotification), arg0, arg1, arg2)
}
